### ISSUE TITLE
AttributeError: 'SerialIO' object has no attribute 'sio'

### ISSUE THREAD

**Issue by rapbando** [jhart99/a6tools#1]
```
user@kali:~/a6tools-asyncio$ ls /dev/ttyUSB*
/dev/ttyUSB0
user@kali:~/a6tools-asyncio$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 003: ID 1a86:7523 QinHeng Electronics CH340 serial converter
Bus 002 Device 002: ID 80ee:0021 VirtualBox USB Tablet
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
user@kali:~/a6tools-asyncio$ python3  radiodump-ng.py
Traceback (most recent call last):
  File "/home/hacker/a6tools-asyncio/radiodump-ng.py", line 39, in <module>
    uart = SerialIO(args.port, args.baudrate, args.verbosity)
  File "/home/hacker/a6tools-asyncio/a6/serialio.py", line 30, in __new__
    it.init(*args, **kwargs)
  File "/home/hacker/a6tools-asyncio/a6/serialio.py", line 47, in init
    self.sio = serial.Serial(port, baudrate, 
AttributeError: module 'serial' has no attribute 'Serial'
Exception ignored in: <function SerialIO.__del__ at 0x7f452a28fe20>
Traceback (most recent call last):
  File "/home/hacker/a6tools-asyncio/a6/serialio.py", line 62, in __del__
AttributeError: 'SerialIO' object has no attribute 'sio'
user@kali:~/a6tools-asyncio$ 

```

Any idea why this happens?

**Comment by rapbando** [comment]
Had to do `pip uninstall serial` and install both pyserial  and  pyserial-asyncio, now is working.
